import type {Metadata} from "next";
import {Figtree} from 'next/font/google'
import localFont from 'next/font/local'
import "./globals.css";
import HeaderComponent from "@/ui/components/header/header.component";
import FooterComponent from "@/ui/components/footer/footer.component";

const figtree = Figtree({
    display: 'swap',
    subsets: ["latin"],
    weight: ['300', '400', '500', '600', '700', '800', '900'],
    variable: "--font-figtree"
});

const yekanBakh = localFont({
    display: 'swap',
    src: [
        {
            path: '../../public/fonts/yekanbakh/thin.ttf',
            weight: '100',
            style: 'normal'
        },
        {
            path: '../../public/fonts/yekanbakh/light.ttf',
            weight: '300',
            style: 'normal'
        },
        {
            path: '../../public/fonts/yekanbakh/regular.ttf',
            weight: '400',
            style: 'normal'
        },
        {
            path: '../../public/fonts/yekanbakh/semibold.ttf',
            weight: '600',
            style: 'normal'
        },
        {
            path: '../../public/fonts/yekanbakh/bold.ttf',
            weight: '700',
            style: 'normal'
        },
        {
            path: '../../public/fonts/yekanbakh/black.ttf',
            weight: '900',
            style: 'normal'
        }
    ],
    variable: "--font-yekanbakh",
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html dir={"rtl"} className={`${figtree.variable} ${yekanBakh.variable}`}>
        <body className={"min-h-screen grid grid-rows-[80px_1fr_auto] bg-gray-800 text-neutral-content"}>
        <HeaderComponent/>
        {children}
        <FooterComponent/>
        </body>
        </html>
    );
}
